In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
res_df=pd.read_csv('C:\\Users\\arhum\\Desktop\\SmartChef-AI\\datasets\\recipes_master.csv')
res_ing_df=pd.read_csv('C:\\Users\\arhum\\Desktop\\SmartChef-AI\\datasets\\recipe_ingredients.csv')
print("Total recipes:", res_df.shape[0])
print("Total ingredients:", res_ing_df.shape[0])

Total recipes: 9997
Total ingredients: 103908

In [3]:
df=pd.merge(res_df,res_ing_df,on='recipe_id',how='inner')

In [4]:
df.shape

(103908, 27)

In [5]:
df.head(4)

,recipe_id,recipe_name,cuisine,category_x,cooking_method,difficulty,prep_time_minutes,cook_time_minutes,total_time_minutes,servings,...,review_count,calories_per_serving,estimated_cost_usd,date_added,is_traditional,is_festival_special,ingredient_number,ingredient_name,quantity,category_y
0,RCP00001,Sajji,Pakistani,Main Course,Baked,Medium,43,129,172,7,...,2070,500,9.2,2024-12-02,False,True,1,Onion,1 medium,Vegetables
1,RCP00001,Sajji,Pakistani,Main Course,Baked,Medium,43,129,172,7,...,2070,500,9.2,2024-12-02,False,True,2,Garlic,6 cloves,Vegetables
2,RCP00001,Sajji,Pakistani,Main Course,Baked,Medium,43,129,172,7,...,2070,500,9.2,2024-12-02,False,True,3,Salt,to taste,Others
3,RCP00001,Sajji,Pakistani,Main Course,Baked,Medium,43,129,172,7,...,2070,500,9.2,2024-12-02,False,True,4,Shrimp,933g,Proteins

In [6]:
df.columns

Index(['recipe_id', 'recipe_name', 'cuisine', 'category_x', 'cooking_method',
       'difficulty', 'prep_time_minutes', 'cook_time_minutes',
       'total_time_minutes', 'servings', 'spice_level', 'meal_type',
       'is_vegetarian', 'is_vegan', 'is_gluten_free', 'is_halal', 'rating',
       'review_count', 'calories_per_serving', 'estimated_cost_usd',
       'date_added', 'is_traditional', 'is_festival_special',
       'ingredient_number', 'ingredient_name', 'quantity', 'category_y'],
      dtype='object')

In [7]:
df[['recipe_id', 'recipe_name', 'ingredient_name']]

       recipe_id  recipe_name ingredient_name
0       RCP00001        Sajji           Onion
1       RCP00001        Sajji          Garlic
2       RCP00001        Sajji            Salt
3       RCP00001        Sajji          Shrimp
4       RCP00001        Sajji         Chicken
...          ...          ...             ...
103903  RCP09997  Dahi Bhalla          Yogurt
103904  RCP09997  Dahi Bhalla     Lemon Juice
103905  RCP09997  Dahi Bhalla       Coriander
103906  RCP09997  Dahi Bhalla            Peas
103907  RCP09997  Dahi Bhalla         Chicken

[103908 rows x 3 columns]

In [8]:
res_n=df[['recipe_id','recipe_name']].drop_duplicates()

In [9]:
res_ind=df.groupby('recipe_id',)['ingredient_name'].apply(list).reset_index()

In [10]:
data=pd.merge(res_n,res_ind,on='recipe_id',how='inner')

In [11]:
data.head()

  recipe_id     recipe_name                                    ingredient_name
0  RCP00001           Sajji  [Onion, Garlic, Salt, Shrimp, Chicken, Oil, Wh...
1  RCP00002     Dal Makhani  [Onion, Garlic, Salt, Paneer, Shrimp, Chickpea...
2  RCP00003      Aloo Gosht  [Onion, Garlic, Salt, Paneer, Mint Leaves, Spi...
3  RCP00004  Sindhi Biryani  [Onion, Garlic, Salt, Chickpeas, All-Purpose F...
4  RCP00005          Haleem  [Onion, Garlic, Salt, Fish, Mutton, Beef, Bay ...

In [12]:
d=df.groupby('recipe_id')['ingredient_name'].apply(', '.join).reset_index()

In [13]:
# Show all columns and rows without truncation
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

In [14]:
d.loc[d['ingredient_name'].apply(len).idxmax()]

recipe_id                                                                                                                                                                                                                                                 RCP05794
ingredient_name    Onion, Garlic, Salt, Mutton, Tamarind Paste, Fresh Coriander, Basmati Rice, Cream, Fenugreek Leaves, Cumin, All-Purpose Flour, Coconut Milk, Basmati Rice, All-Purpose Flour, Chickpea Flour, All-Purpose Flour, Mint Leaves, Green Chili, Salt
Name: 5793, dtype: object

In [15]:
data.head()

,recipe_id,recipe_name,ingredient_name
0,RCP00001,Sajji,"[Onion, Garlic, Salt, Shrimp, Chicken, Oil, Wheat Flour, Sugar, Mustard Seeds, Mutton, Fenugreek Leaves]"
1,RCP00002,Dal Makhani,"[Onion, Garlic, Salt, Paneer, Shrimp, Chickpea Flour, Butter]"
2,RCP00003,Aloo Gosht,"[Onion, Garlic, Salt, Paneer, Mint Leaves, Spinach, Potato, Carrot]"
3,RCP00004,Sindhi Biryani,"[Onion, Garlic, Salt, Chickpeas, All-Purpose Flour, All-Purpose Flour, Eggs, Vinegar]"
4,RCP00005,Haleem,"[Onion, Garlic, Salt, Fish, Mutton, Beef, Bay Leaf, Ghee, Raisins, Ginger, Water, Fenugreek Leaves]"

In [16]:
data["ingredient_name"]=data["ingredient_name"].apply(
    lambda lst: list(dict.fromkeys(
        item.strip().lower() for item in lst
    ))
)

In [17]:
data.loc[data["ingredient_name"].apply(len).idxmax()]

recipe_id                                                                                                                                                                                      RCP01157
recipe_name                                                                                                                                                                                  Aloo Gosht
ingredient_name    [onion, garlic, salt, tofu, vinegar, basmati rice, ghee, cloves, fenugreek leaves, sugar, lemon juice, cream, ginger, chickpea flour, raisins, cashews, potato, fish, mustard seeds]
Name: 1156, dtype: object

In [18]:
data["ingredient_name"] = data["ingredient_name"].apply(
    lambda x: sorted(x, key=str.lower)
)

In [19]:
ingredients = [
    "Basmati Rice", "Cashews", "Chickpea Flour", "Cloves", "Cream",
    "Fenugreek Leaves", "Fish", "Garlic", "Ghee", "Ginger",
    "Lemon Juice", "Mustard Seeds", "Onion", "Potato", "Raisins",
    "Salt", "Sugar", "Tofu", "Vinegar"
]

In [20]:
df=data.copy()

In [21]:
df.head()

,recipe_id,recipe_name,ingredient_name
0,RCP00001,Sajji,"[chicken, fenugreek leaves, garlic, mustard seeds, mutton, oil, onion, salt, shrimp, sugar, wheat flour]"
1,RCP00002,Dal Makhani,"[butter, chickpea flour, garlic, onion, paneer, salt, shrimp]"
2,RCP00003,Aloo Gosht,"[carrot, garlic, mint leaves, onion, paneer, potato, salt, spinach]"
3,RCP00004,Sindhi Biryani,"[all-purpose flour, chickpeas, eggs, garlic, onion, salt, vinegar]"
4,RCP00005,Haleem,"[bay leaf, beef, fenugreek leaves, fish, garlic, ghee, ginger, mutton, onion, raisins, salt, water]"

In [22]:
unique_ingredients = sorted(
    df["ingredient_name"].explode().unique()
)

print(unique_ingredients)
print(len(unique_ingredients))

['all-purpose flour', 'almonds', 'basmati rice', 'bay leaf', 'beef', 'bell pepper', 'black pepper', 'butter', 'cardamom', 'carrot', 'cashews', 'cauliflower', 'chicken', 'chickpea flour', 'chickpeas', 'cinnamon', 'cloves', 'coconut milk', 'coriander', 'cream', 'cumin', 'curry leaves', 'eggs', 'fenugreek leaves', 'fish', 'fresh coriander', 'garam masala', 'garlic', 'ghee', 'ginger', 'green chili', 'lemon juice', 'lentils (dal)', 'milk', 'mint leaves', 'mustard seeds', 'mutton', 'oil', 'onion', 'paneer', 'peas', 'potato', 'raisins', 'red chili powder', 'salt', 'semolina', 'sesame seeds', 'shrimp', 'spinach', 'sugar', 'tamarind paste', 'tofu', 'tomato', 'turmeric', 'vinegar', 'water', 'wheat flour', 'yogurt']
58

In [23]:
for ingredient in unique_ingredients:
    df[ingredient] = df["ingredient_name"].apply(
        lambda x: int(ingredient in x)
    )

In [24]:
df=df.drop(["recipe_id","ingredient_name"],axis=1)

In [25]:
df.head()

,recipe_name,all-purpose flour,almonds,basmati rice,bay leaf,beef,bell pepper,black pepper,butter,cardamom,carrot,cashews,cauliflower,chicken,chickpea flour,chickpeas,cinnamon,cloves,coconut milk,coriander,cream,cumin,curry leaves,eggs,fenugreek leaves,fish,fresh coriander,garam masala,garlic,ghee,ginger,green chili,lemon juice,lentils (dal),milk,mint leaves,mustard seeds,mutton,oil,onion,paneer,peas,potato,raisins,red chili powder,salt,semolina,sesame seeds,shrimp,spinach,sugar,tamarind paste,tofu,tomato,turmeric,vinegar,water,wheat flour,yogurt
0,Sajji,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0
1,Dal Makhani,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
2,Aloo Gosht,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,1,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0
3,Sindhi Biryani,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0
4,Haleem,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,1,0,0,0,0,0,0,1,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0

In [26]:
df.to_csv("Recipe_ingrediect.csv", index=False)

### Recipe Nutritions dataset

In [33]:
df1=pd.read_csv("C:\\Users\\arhum\\Desktop\\SmartChef-AI\\datasets\\recipe_nutrition.csv")

In [34]:
df1.head()

,recipe_id,calories,protein_g,carbohydrates_g,fat_g,fiber_g,sugar_g,sodium_mg,cholesterol_mg,vitamin_a_percent,vitamin_c_percent,calcium_percent,iron_percent
0,RCP00001,500,45,54,28,10,18,691,83,9,30,10,39
1,RCP00002,264,43,78,21,13,11,435,10,15,49,23,30
2,RCP00003,596,24,42,30,4,13,1268,64,19,27,15,19
3,RCP00004,522,13,34,27,7,8,1311,3,17,42,28,21
4,RCP00005,277,32,33,16,3,6,1475,55,12,34,20,27

In [35]:
df1.shape

(9997, 13)

In [56]:
df2=data[['recipe_id','recipe_name']]

In [40]:
df2.head()

  recipe_id     recipe_name
0  RCP00001           Sajji
1  RCP00002     Dal Makhani
2  RCP00003      Aloo Gosht
3  RCP00004  Sindhi Biryani
4  RCP00005          Haleem

In [41]:
df2.shape

(9997, 2)

In [45]:
data1=pd.merge(df2,df1,on='recipe_id',how='inner')

In [46]:
data1.shape

(9997, 14)

In [47]:
data1.head()

,recipe_id,recipe_name,calories,protein_g,carbohydrates_g,fat_g,fiber_g,sugar_g,sodium_mg,cholesterol_mg,vitamin_a_percent,vitamin_c_percent,calcium_percent,iron_percent
0,RCP00001,Sajji,500,45,54,28,10,18,691,83,9,30,10,39
1,RCP00002,Dal Makhani,264,43,78,21,13,11,435,10,15,49,23,30
2,RCP00003,Aloo Gosht,596,24,42,30,4,13,1268,64,19,27,15,19
3,RCP00004,Sindhi Biryani,522,13,34,27,7,8,1311,3,17,42,28,21
4,RCP00005,Haleem,277,32,33,16,3,6,1475,55,12,34,20,27

In [50]:
data1=data1.drop("recipe_id",axis=1)

In [51]:
data1.to_csv("Recipe_nutrition.csv", index=False)

### Steps dataset

In [58]:
df3=pd.read_csv("C:\\Users\\arhum\\Desktop\\SmartChef-AI\\datasets\\recipe_steps.csv")

In [59]:
df3.head()

,recipe_id,step_number,step_description,estimated_time_minutes
0,RCP00001,1,Soak rice in water for 20 minutes,10
1,RCP00001,2,Wash and chop all vegetables into desired sizes,13
2,RCP00001,3,Add all powdered spices and mix well,2
3,RCP00001,4,Add tomatoes and cook until they soften,2
4,RCP00001,5,Add the marinated protein and cook until browned,12

In [64]:
df3.shape

(84616, 4)

In [57]:
df2.head()

  recipe_id     recipe_name
0  RCP00001           Sajji
1  RCP00002     Dal Makhani
2  RCP00003      Aloo Gosht
3  RCP00004  Sindhi Biryani
4  RCP00005          Haleem

In [60]:
data2=pd.merge(df2,df3,on='recipe_id',how='inner')

In [65]:
data2.head(10)

,recipe_id,recipe_name,step_number,step_description,estimated_time_minutes
0,RCP00001,Sajji,1,Soak rice in water for 20 minutes,10
1,RCP00001,Sajji,2,Wash and chop all vegetables into desired sizes,13
2,RCP00001,Sajji,3,Add all powdered spices and mix well,2
3,RCP00001,Sajji,4,Add tomatoes and cook until they soften,2
4,RCP00001,Sajji,5,Add the marinated protein and cook until browned,12
5,RCP00001,Sajji,6,Adjust seasoning with salt and pepper,10
6,RCP00001,Sajji,7,Add ginger-garlic paste and cook for 2 minutes,2
7,RCP00001,Sajji,8,Let it rest for 5 minutes before serving,10
8,RCP00001,Sajji,9,Garnish with fresh coriander and mint leaves,3
9,RCP00002,Dal Makhani,1,Prepare all ingredients and keep them ready (mise en place),8

In [62]:
data2.shape

(84616, 5)

In [67]:
data2=data2.drop('recipe_id',axis=1)

In [68]:
data2.to_csv("Recipe_steps.csv", index=False)